/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MissaoRouteImport } from './routes/missao'
import { Route as PeregrinoRouteImport } from './routes/peregrino'
import { Route as ProdutoRouteImport } from './routes/produto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoRoute = MissaoRouteImport.update({
  id: '/missao',
  path: '/missao',
  getParentRoute: () => rootRouteImport,
} as any)
const PeregrinoRoute = PeregrinoRouteImport.update({
  id: '/peregrino',
  path: '/peregrino',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/journal': typeof JournalRoute
  '/missao': typeof MissaoRoute
  '/peregrino': typeof PeregrinoRoute
  '/produto': typeof ProdutoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/journal': typeof JournalRoute
  '/missao': typeof MissaoRoute
  '/peregrino': typeof PeregrinoRoute
  '/produto': typeof ProdutoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/journal': typeof JournalRoute
  '/missao': typeof MissaoRoute
  '/peregrino': typeof PeregrinoRoute
  '/produto': typeof ProdutoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/historia' | '/journal' | '/missao' | '/peregrino' | '/produto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historia' | '/journal' | '/missao' | '/peregrino' | '/produto'
  id:
    | '__root__'
    | '/'
    | '/historia'
    | '/journal'
    | '/missao'
    | '/peregrino'
    | '/produto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriaRoute: typeof HistoriaRoute
  JournalRoute: typeof JournalRoute
  MissaoRoute: typeof MissaoRoute
  PeregrinoRoute: typeof PeregrinoRoute
  ProdutoRoute: typeof ProdutoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao': {
      id: '/missao'
      path: '/missao'
      fullPath: '/missao'
      preLoaderRoute: typeof MissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peregrino': {
      id: '/peregrino'
      path: '/peregrino'
      fullPath: '/peregrino'
      preLoaderRoute: typeof PeregrinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriaRoute: HistoriaRoute,
  JournalRoute: JournalRoute,
  MissaoRoute: MissaoRoute,
  PeregrinoRoute: PeregrinoRoute,
  ProdutoRoute: ProdutoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
