/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as MissaoRouteImport } from './routes/missao'
import { Route as PeregrinoRouteImport } from './routes/peregrino'
import { Route as ProdutoIndexRouteImport } from './routes/produto/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoRoute = MissaoRouteImport.update({
  id: '/missao',
  path: '/missao',
  getParentRoute: () => rootRouteImport,
} as any)
const PeregrinoRoute = PeregrinoRouteImport.update({
  id: '/peregrino',
  path: '/peregrino',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIndexRoute = ProdutoIndexRouteImport.update({
  id: '/produto/',
  path: '/produto/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/historia': typeof HistoriaRoute
  '/journal': typeof JournalRoute
  '/missao': typeof MissaoRoute
  '/peregrino': typeof PeregrinoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/produto/': typeof ProdutoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/historia': typeof HistoriaRoute
  '/journal': typeof JournalRoute
  '/missao': typeof MissaoRoute
  '/peregrino': typeof PeregrinoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/produto': typeof ProdutoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/carrinho': typeof CarrinhoRoute
  '/catalogo': typeof CatalogoRoute
  '/historia': typeof HistoriaRoute
  '/journal': typeof JournalRoute
  '/missao': typeof MissaoRoute
  '/peregrino': typeof PeregrinoRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/produto/': typeof ProdutoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/catalogo'
    | '/historia'
    | '/journal'
    | '/missao'
    | '/peregrino'
    | '/produto/$slug'
    | '/produto/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrinho'
    | '/catalogo'
    | '/historia'
    | '/journal'
    | '/missao'
    | '/peregrino'
    | '/produto/$slug'
    | '/produto'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/carrinho'
    | '/catalogo'
    | '/historia'
    | '/journal'
    | '/missao'
    | '/peregrino'
    | '/produto/$slug'
    | '/produto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CatalogoRoute: typeof CatalogoRoute
  HistoriaRoute: typeof HistoriaRoute
  JournalRoute: typeof JournalRoute
  MissaoRoute: typeof MissaoRoute
  PeregrinoRoute: typeof PeregrinoRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ProdutoIndexRoute: typeof ProdutoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao': {
      id: '/missao'
      path: '/missao'
      fullPath: '/missao'
      preLoaderRoute: typeof MissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peregrino': {
      id: '/peregrino'
      path: '/peregrino'
      fullPath: '/peregrino'
      preLoaderRoute: typeof PeregrinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/': {
      id: '/produto/'
      path: '/produto'
      fullPath: '/produto/'
      preLoaderRoute: typeof ProdutoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CarrinhoRoute: CarrinhoRoute,
  CatalogoRoute: CatalogoRoute,
  HistoriaRoute: HistoriaRoute,
  JournalRoute: JournalRoute,
  MissaoRoute: MissaoRoute,
  PeregrinoRoute: PeregrinoRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ProdutoIndexRoute: ProdutoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
